# Generated by Django 4.1.6 on 2023-02-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageUpload',
            new_name='Image',
        ),
    ]
