# Generated by Django 4.1.6 on 2023-02-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_app', '0002_rename_imageupload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='chat_images/'),
        ),
    ]
