# Generated by Django 4.1.6 on 2023-03-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_app', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='type',
            field=models.CharField(choices=[('Conversation', 'Conversation'), ('Group Chat', 'Group Chat')], default='Conversation', max_length=128),
        ),
    ]
