# Generated by Django 4.1.6 on 2023-03-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel_app', '0005_alter_chatroom_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='conversation',
            new_name='chatroom',
        ),
    ]
