# Generated by Django 4.1.6 on 2023-03-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_app', '0007_alter_message_read_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
    ]
